version: "3"
services:
  db:
    image: "postgres"
    container_name: "techtrading_postgres"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=passw0rd
      - POSTGRES_DB=techtrading
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data