spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreply.techtrading@gmail.com
    password: techtrading3#
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
  datasource:
    #url: ${SPRING_DATASOURCE_URL}
    #username: ${SPRING_DATASOURCE_USERNAME}
    #password: ${SPRING_DATASOURCE_PASSWORD}
    platform: postgres
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  application:
    name: techtrading