INSERT INTO SYMBOL_TYPE(ID,DESCRIPTION) VALUES('COMMODITY','Commodity symbol');
INSERT INTO SYMBOL(ID,COMPANY,DESCRIPTION,SYMBOL_TYPE) VALUES('NG','Natural Gas','Natural Gas','COMMODITY');
INSERT INTO CONTRACT_TYPE(ID,DESCRIPTION) VALUES('FUTURES','Futures contract');
INSERT INTO CONTRACT(ID, DESCRIPTION, END_DATE, IS_ACTIVE, KITE_CHART_ID, START_DATE, CONTRACT_TYPE, SYMBOL) VALUES('NGJAN20','Natural Gas Futures contract - January 2020','2020-01-28',TRUE,'55592455','2019-12-26','FUTURES','NG');
INSERT INTO CONTRACT(ID, DESCRIPTION, END_DATE, IS_ACTIVE, KITE_CHART_ID, START_DATE, CONTRACT_TYPE, SYMBOL) VALUES('NGFEB20','Natural Gas Futures contract - February 2020','2020-02-25',TRUE,'55648519','2019-12-26','FUTURES','NG');