INSERT INTO SYMBOL_TYPE VALUES('COMMODITY','Commodity symbol');
INSERT INTO SYMBOL VALUES('NG','Natural Gas','Natural Gas','COMMODITY');
INSERT INTO CONTRACT_TYPE VALUES('FUTURES','Futures contract');